### ISSUE TITLE
Expose name and block_size attributes in Hash class

### ISSUE THREAD

**Issue by alexmgr** [DinoTools/python-ssdeep#39]
##### ISSUE TYPE
- Feature Idea

##### Python ssdeep VERSION
```
$ pip freeze | grep ssdeep
ssdeep==3.3
```

##### OS / ENVIRONMENT

**OS**:
- OSX

**Python version**:
- Python 2.7

**ssdeep lib**:
- provided by system
```
$ brew info ssdeep | grep ssdeep
ssdeep: stable 2.14.1 (bottled)
https://ssdeep-project.github.io/ssdeep/
/usr/local/Cellar/ssdeep/2.14.1 (15 files, 144.9KB) *
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ssdeep.rb
```

##### SUMMARY
Would be nice if ssdeep `Hash` class exposed the meaningful attributes of the `hashlib` interface:
```
>>> dir(md5)
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'block_size', 'copy', 'digest', 'digest_size', 'digestsize'
, 'hexdigest', 'name', 'update']
```
I think `name` and `block_size` would make sense?

##### STEPS TO REPRODUCE
```
>>> import ssdeep
>>> c = ssdeep.Hash()
>>> c.name
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    c.name
AttributeError: 'Hash' object has no attribute 'name'
>>> c.block_size
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    c.block_size
AttributeError: 'Hash' object has no attribute 'block_size'
```

##### EXPECTED RESULTS
```>>> import ssdeep
>>> c = ssdeep.Hash()
>>> c.name
'ssdeep'
>>> c.block_size
8
```

**Comment by phibos** [comment]
Thanks for sharing your idea. The issues has been fixed and will be release in version 3.4 soon.
