### ISSUE TITLE
pip install unsuccessfully

### ISSUE THREAD

**Issue by gaohang** [DinoTools/python-ssdeep#64]
os win10
cmd: pip install ssdeep
result:
......  Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I tried in centos and got the same error. why?  how to fix it?

**Comment by phibos** [comment]
Thanks for reporting the issue. Please attach your logs.

**Comment by segelbaot** [comment]
iam not gaohang, but i think iam having the same problem.


log:
C:\Users\user>pip3 install ssdeep
Collecting ssdeep
  Using cached ssdeep-3.4.tar.gz (110 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      running egg_info
      creating C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-iwhhf2w4\ssdeep.egg-info
      writing C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-iwhhf2w4\ssdeep.egg-info\PKG-INFO
      writing dependency_links to C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-iwhhf2w4\ssdeep.egg-info\dependency_links.txt
      writing requirements to C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-iwhhf2w4\ssdeep.egg-info\requires.txt
      writing top-level names to C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-iwhhf2w4\ssdeep.egg-info\top_level.txt
      writing manifest file 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-iwhhf2w4\ssdeep.egg-info\SOURCES.txt'
      _ssdeep_cffi_a28e5628x27adcb8d.c
      src\ssdeep\__pycache__\_ssdeep_cffi_a28e5628x27adcb8d.c(266): fatal error C1083: Cannot open include file: 'fuzzy.h': No such file or directory
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 401, in compile
          self.spawn(args)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 507, in spawn
          return super().spawn(cmd)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\ccompiler.py", line 910, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\spawn.py", line 91, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      During handling of the above exception, another exception occurred:
      Traceback (most recent call last):
        File "c:\users\user\appdata\local\temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\.eggs\cffi-1.15.1-py3.10-win-amd64.egg\cffi\ffiplatform.py", line 51, in _build
          dist.run_command('build_ext')
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 340, in run
          self.build_extensions()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\_msvccompiler.py", line 403, in compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      During handling of the above exception, another exception occurred:
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\setup.py", line 108, in <module>
          setup(
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\egg_info.py", line 299, in run
          self.find_sources()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\egg_info.py", line 306, in find_sources
          mm.run()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\egg_info.py", line 541, in run
          self.add_defaults()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\command\sdist.py", line 226, in add_defaults
          self._add_defaults_python()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\sdist.py", line 107, in _add_defaults_python
          build_py = self.get_finalized_command('build_py')
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 299, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\build_py.py", line 29, in finalize_options
          orig.build_py.finalize_options(self)
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\command\build_py.py", line 43, in finalize_options
          self.set_undefined_options('build',
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 287, in set_undefined_options
          src_cmd_obj.ensure_finalized()
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "C:\Users\user\AppData\Local\Temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\setup.py", line 24, in finalize_options
          self.distribution.ext_modules = get_ext_modules()
        File "C:\Users\user\AppData\Local\Temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\setup.py", line 79, in get_ext_modules
          binding.verify()
        File "C:\Users\user\AppData\Local\Temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\src\ssdeep\binding.py", line 126, in verify
          self._lib = self.ffi.verify(
        File "c:\users\user\appdata\local\temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\.eggs\cffi-1.15.1-py3.10-win-amd64.egg\cffi\api.py", line 468, in verify
          lib = self.verifier.load_library()
        File "c:\users\user\appdata\local\temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\.eggs\cffi-1.15.1-py3.10-win-amd64.egg\cffi\verifier.py", line 105, in load_library
          self._compile_module()
        File "c:\users\user\appdata\local\temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\.eggs\cffi-1.15.1-py3.10-win-amd64.egg\cffi\verifier.py", line 202, in _compile_module
          outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
        File "c:\users\user\appdata\local\temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\.eggs\cffi-1.15.1-py3.10-win-amd64.egg\cffi\ffiplatform.py", line 22, in compile
          outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
        File "c:\users\user\appdata\local\temp\pip-install-vog2wji6\ssdeep_d122080f99814855be407f705e89b9b3\.eggs\cffi-1.15.1-py3.10-win-amd64.egg\cffi\ffiplatform.py", line 58, in _build
          raise VerificationError('%s: %s' % (e.__class__.__name__, e))
      cffi.VerificationError: CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Doudnox** [comment]
same problem

Fix following this : https://python-ssdeep.readthedocs.io/en/latest/installation.html#install-on-ubuntu-16-04
