### ISSUE TITLE
Error when trying to install on Windows

### ISSUE THREAD

**Issue by pchaigno** [DinoTools/python-ssdeep#8]
I'm trying to install python-ssdeep on Windows 7 32bit with MinGW.
I have Python 2.7 and MinGW 4.8 installed on a new VM.

When I run `python setup.py build -c mingw32` I get the following error:

```
Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    ext_package="ssdeep",
  File "c:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "c:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\Python27\lib\distutils\dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "c:\Python27\lib\distutils\cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 19, in finalize_options
    self.distribution.ext_modules = get_ext_modules()
  File "setup.py", line 67, in get_ext_modules
    binding.verify()
  File "c:\python-ssdeep\ssdeep\binding.py", line 125, in verify
    libraries=self._libraries,
  File "c:\Python27\lib\site-packages\cffi\api.py", line 340, in verify
    lib = self.verifier.load_library()
  File "c:\Python27\lib\site-packages\cffi\verifier.py", line 75, in load_library
    return self._load_library()
  File "c:\Python27\lib\site-packages\cffi\verifier.py", line 151, in _load_library
    return self._vengine.load_library()
  File "c:\Python27\lib\site-packages\cffi\vengine_cpy.py", line 149, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing 'c:\\python-ssdeep\\ssdeep\\__pycache__\\_ssdeep_cffi_b2f2ace7x627c7d55.pyd': DLL load failed: The specified module could not be found.
```

I made sure the installation of ssdeep worked well manually (`./configure`, `make` and `make install`). It generated thee files: `libfuzzy.a`, `libfuzzy.dll.a` and `libfuzzy.la`.

Any idea on what the problem may be?

**Comment by oasec1** [comment]
Can you elaborate more on how you used this option during the installation in windows?

Thanks,
Robert

**Comment by pchaigno** [comment]
@oasec1 I simply used `export BUILD_LIB=1`.

**Comment by ooker777** [comment]
Take a look at [MacDue/ssdeep-windows-32_64: ssdeep for python on windows](https://github.com/MacDue/ssdeep-windows-32_64)
